### model
model_name_or_path: meta-llama/Meta-Llama-3-8B

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z2_config.json

### dataset
dataset: leandojo_benchmark_4_train
template: llama3
cutoff_len: 2048
max_samples: null
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/llama3-8b/leandojo
logging_steps: 10
save_steps: 1959
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 8
gradient_accumulation_steps: 2
learning_rate: 1.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
do_eval: true
eval_dataset: leandojo_benchmark_4_val
per_device_eval_batch_size: 8
eval_strategy: steps
eval_steps: 1959
